version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a node version: 10, 12, 14
        VARIANT: 12
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    # [Optional] Allows MongoDB to be accessed from localhost, or forwarded to your local machine when in VS Code.
    entrypoint: "/usr/local/share/mongo-proxy.sh"

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Use the "forwardPorts" property in **devcontainer.json** to forward an app port
    # locally since the "ports" property in this file will not forward from a Codespace.

    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: node

  mongo:
    # Note: The MongoDB host name is "mongo" by default, not "localhost"
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - /data/db
    
    # Uncomment to change startup options
    # environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    #  MONGO_INITDB_DATABASE: your-database-here

    # To access MongoDB from an external tool when connected from VS Code, add port **27017** 
    # to the "forwardPorts" property in **devcontainer.json**. Adding the "ports" property to 
    # this file will not publish the port to your local machine when you connect to a Codespace.


